steps:
- name: 'docker/compose:1.23.2'
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_vs-proxy:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--image-url', 'workspace_vs-proxy:latest']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
